from django.db import models

# Create your models here.

class VisaApplication(models.Model):
    CASE_NUMBER = models.CharField(max_length=255)
    CASE_STATUS = models.CharField(max_length=255)
    CASE_SUBMITTED = models.DateField()
    DECISION_DATE = models.DateField()
    VISA_CLASS = models.CharField(max_length=255)
    EMPLOYMENT_START_DATE = models.DateField()
    EMPLOYMENT_END_DATE = models.DateField()
    EMPLOYER_NAME = models.CharField(max_length=255)
    EMPLOYER_ADDRESS = models.CharField(max_length=255)
    EMPLOYER_CITY = models.CharField(max_length=255)
    EMPLOYER_STATE = models.CharField(max_length=255)
    EMPLOYER_POSTAL_CODE = models.CharField(max_length=10)
    EMPLOYER_COUNTRY = models.CharField(max_length=255)
    EMPLOYER_PROVINCE = models.CharField(max_length=255)
    EMPLOYER_PHONE = models.CharField(max_length=20)
    EMPLOYER_PHONE_EXT = models.CharField(max_length=10)
    AGENT_ATTORNEY_NAME = models.CharField(max_length=255)
    AGENT_ATTORNEY_CITY = models.CharField(max_length=255)
    AGENT_ATTORNEY_STATE = models.CharField(max_length=255)
    JOB_TITLE = models.CharField(max_length=255)
    SOC_CODE = models.CharField(max_length=10)
    SOC_NAME = models.CharField(max_length=255)
    NAIC_CODE = models.FloatField()
    TOTAL_WORKERS = models.IntegerField()
    FULL_TIME_POSITION = models.BooleanField()
    PREVAILING_WAGE = models.FloatField()
    PW_UNIT_OF_PAY = models.CharField(max_length=255)
    PW_WAGE_SOURCE = models.CharField(max_length=255)
    PW_SOURCE_YEAR = models.FloatField()
    PW_SOURCE_OTHER = models.CharField(max_length=255)
    WAGE_RATE_OF_PAY_FROM = models.FloatField()
    WAGE_RATE_OF_PAY_TO = models.FloatField()
    WAGE_UNIT_OF_PAY = models.CharField(max_length=255)
    H1B_DEPENDENT = models.CharField(max_length=3)
    WILLFUL_VIOLATOR = models.CharField(max_length=3)
    WORKSITE_CITY = models.CharField(max_length=255)
    WORKSITE_COUNTY = models.CharField(max_length=255)
    WORKSITE_STATE = models.CharField(max_length=255)
    WORKSITE_POSTAL_CODE = models.CharField(max_length=10)
    ORIGINAL_CERT_DATE = models.DateField()