# Generated by Django 4.2.6 on 2023-10-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='FULL_TIME_POSITION',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
