# Generated by Django 4.2.6 on 2023-10-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_visaapplication_full_time_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='AGENT_ATTORNEY_CITY',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='AGENT_ATTORNEY_NAME',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='AGENT_ATTORNEY_STATE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='CASE_STATUS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='CASE_SUBMITTED',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='DECISION_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='EMPLOYER_ADDRESS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='EMPLOYER_CITY',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='EMPLOYER_COUNTRY',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='EMPLOYER_NAME',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='EMPLOYER_PHONE',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='EMPLOYER_PHONE_EXT',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='EMPLOYER_POSTAL_CODE',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='EMPLOYER_PROVINCE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='EMPLOYER_STATE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='EMPLOYMENT_END_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='EMPLOYMENT_START_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='H1B_DEPENDENT',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='JOB_TITLE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='NAIC_CODE',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='ORIGINAL_CERT_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='PW_SOURCE_OTHER',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='PW_SOURCE_YEAR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='PW_WAGE_SOURCE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='SOC_CODE',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='SOC_NAME',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='TOTAL_WORKERS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='WAGE_RATE_OF_PAY_FROM',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='WAGE_RATE_OF_PAY_TO',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='WAGE_UNIT_OF_PAY',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='WILLFUL_VIOLATOR',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='WORKSITE_CITY',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='WORKSITE_COUNTY',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='WORKSITE_POSTAL_CODE',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='WORKSITE_STATE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
