# Generated by Django 4.2.6 on 2023-10-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_visaapplication_prevailing_wage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='EMPLOYER_PHONE_EXT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='WORKSITE_POSTAL_CODE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
