# Generated by Django 4.2.6 on 2023-10-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_visaapplication_employer_phone_ext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='EMPLOYER_POSTAL_CODE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='SOC_CODE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
